name: anjoman
version: 1.0.0+1
publish_to: none
description: The exclusive application of the Computer Engineering Association of Azad University, Quchan branch.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  mysql1: ^0.20.0
  encrypt: ^5.0.1
  envied: ^0.3.0
  responsive_framework: ^0.2.0
  shared_preferences: ^2.1.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/animation/
    - assets/fonts/
  fonts: 
    - family: Mitra
      fonts: 
        - asset: assets/fonts/Mitra.ttf
        - asset: assets/fonts/Mitra_Bold.ttf

    - family: Kara
      fonts: 
        - asset: assets/fonts/Kara_Regular.ttf
        - asset: assets/fonts/Kara_SemiBold.ttf

    - family: Mola
      fonts: 
        - asset: assets/fonts/Mola.ttf
  uses-material-design: true
  generate: true

